(load "main.lisp")
(defparameter file (open "test-phrases.txt"))
(do ((eof nil (not (listen file))))
  (eof)
  (let ((test-case (read-line file)))
    (princ (format nil "Working on ~A~%  " test-case))
    (print (wfp-checker test-case))))